# Workflow to deploy code to AWS EC2 instance
name: Deploy to AWS EC2

on:
  push:
    branches:
      - test  # or your preferred branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'  # Specify your Python version

    # - name: Install Dependencies
    #   run: |
    #     pip install -r requirements.txt

    - name: Test
      run: |
        # Add commands to run your tests

    - name: Deploy to AWS EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2 }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        TARGET: ${{ secrets.TARGET }}
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        sshpass -e scp -o StrictHostKeyChecking=no -r . $USER@$HOST:$TARGET
        sshpass -e ssh -o StrictHostKeyChecking=no $USER@$HOST 'cd $TARGET && python3 manage.py migrate'

